print('___________________Analisador de texto do Craaaudioo________________')
texto = input('digite o seu nome completo: ')
print('Analisando o seu nome......')
print(f'Seu nome é {texto}')
print(f'Seu nome em minúsculas é: {texto.lower()}')
print(f'Seu nome em maiúsculas é: {texto.upper()}')
print(f'Seu nome somente com as iniciais maiúsculas é: {texto.title()}')
print(f'Seu nome tem {len(texto)} letras')
primeiro_nome = texto.split(" ")
print(f'Seu primeiro nome é: {primeiro_nome[0]} e ele tem {len(primeiro_nome[0])} letras')
